apiVersion: apps/v1
kind: Deployment
metadata:
  name: ais-ifm
  labels:
    product: k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ais
      tier: web
  template:
    metadata:
      labels:
        app: ais
        tier: web
    spec:
      containers:
      - name: bootcamp-container
        image: jocatalin/kubernetes-bootcamp:v1
        ports:
        - containerPort: 8080
        resources:
          limits:  
            cpu: 1000m
            memory: 600Mi             
          requests: 
            cpu: 500m
            memory: 300Mi
